#!/bin/bash
# Log time spent on a project in two columns, eg:
# Date   NumHours
# The log is cumulative and new entries are added at the end of the file.

for i in $(find . -name project_timelog.tsv)
do
    echo -ne $i"\t";
    cut -f 2 $i | total
done

